repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: "v1.86.0"
  hooks:
    - id: terraform_fmt
      args:
      - --args=-recursive
      - --args=-no-color
    - id: terraform_docs