formatter: markdown table
output:
  file: README.md
  mode: inject
content: |-
  {{ .Header }}

  ## Example

  ```hcl
  {{ include "examples/main.tf"}}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Modules }}

  {{ .Inputs }}

  {{ .Resources }}

  {{ .Outputs }}

